apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: endereco-api
  annotations:
    github.com/project-slug: SantosCode/endereco-api
spec:
  type: other
  lifecycle: unknown
  owner: team-a
